---
name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0.x
          - 2.7.x
          - 2.6.x
          - 2.5.x
        rails:
          - rails_5.0.7
          - rails_5.1.7
          - rails_5.2.3
          - rails_5.2.4
          - rails_5.2.5
          - rails_5.2.6
          - rails_6.0.4
          - rails_6.1.4
        exclude:
          - ruby: 3.0.x
            rails: rails_5.0.7
          - ruby: 3.0.x
            rails: rails_5.1.7
          - ruby: 3.0.x
            rails: rails_5.2.3
          - ruby: 3.0.x
            rails: rails_5.2.4
          - ruby: 3.0.x
            rails: rails_5.2.5
          - ruby: 3.0.x
            rails: rails_5.2.6

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: |
          export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/${RAILS_VERSION}.gemfile"
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3

      - name: Test
        env:
          RAILS_VERSION: ${{ matrix.rails }}
        run: |
          export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/${RAILS_VERSION}.gemfile"
          bundle exec rake
