name: Release Gem

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    uses: appfolio/rubygems-releaser/.github/workflows/release.yml@v1
