name: Release Gem

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'lib/**'
      - 'store_base_sti_class.gemspec'
      - 'LICENSE.txt'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    uses: appfolio/rubygems-releaser/.github/workflows/release.yml@v1
